-- CaseFlow MVP schema. IDs are UUIDs; auth.users remains the identity source.
create extension if not exists pgcrypto;
create type public.user_role as enum ('student','faculty');
create type public.entry_mode as enum ('acquisition','joint_venture','organic_entry');

create table public.profiles (id uuid primary key references auth.users on delete cascade, display_name text not null, role user_role not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.courses (id uuid primary key default gen_random_uuid(), title text not null, code text not null, faculty_id uuid not null references public.profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.enrollments (course_id uuid references public.courses on delete cascade, user_id uuid references public.profiles on delete cascade, role user_role not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(course_id,user_id));
create table public.cases (id uuid primary key default gen_random_uuid(), title text not null, summary text not null, is_fictional boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.case_sources (id uuid primary key default gen_random_uuid(), case_id uuid not null references public.cases on delete cascade, source_key text not null, title text not null, content text not null, storage_path text, mime_type text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(case_id,source_key));
create table public.assignments (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses on delete cascade, case_id uuid not null references public.cases, due_at timestamptz, diagnostic_questions jsonb not null default '[]', decision_options jsonb not null default '[]', rubric jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.learning_objectives (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references public.assignments on delete cascade, objective text not null, sort_order int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.student_attempts (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references public.assignments on delete cascade, student_id uuid not null references public.profiles, status text not null check(status in ('not_started','in_progress','completed')), started_at timestamptz default now(), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(assignment_id,student_id));
create table public.student_responses (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.student_attempts on delete cascade, response_type text not null, content text not null, source_ids text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.ai_conversations (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.student_attempts on delete cascade, messages jsonb not null default '[]', model text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.decision_checkpoints (id uuid primary key default gen_random_uuid(), attempt_id uuid not null unique references public.student_attempts on delete cascade, decision entry_mode not null, rationale text not null, key_risk text not null, mitigation text not null, confidence int not null check(confidence between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.preparation_briefs (id uuid primary key default gen_random_uuid(), attempt_id uuid not null unique references public.student_attempts on delete cascade, content jsonb not null, released_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.reflections (id uuid primary key default gen_random_uuid(), attempt_id uuid not null unique references public.student_attempts on delete cascade, content text not null, comparison jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.faculty_insights (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references public.assignments on delete cascade, insight_type text not null, content jsonb not null, source_response_count int not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index assignments_course_idx on public.assignments(course_id);
create index attempts_assignment_status_idx on public.student_attempts(assignment_id,status);
create index responses_attempt_idx on public.student_responses(attempt_id);
create index insights_assignment_idx on public.faculty_insights(assignment_id);

alter table public.profiles enable row level security; alter table public.courses enable row level security; alter table public.enrollments enable row level security; alter table public.cases enable row level security; alter table public.case_sources enable row level security; alter table public.assignments enable row level security; alter table public.learning_objectives enable row level security; alter table public.student_attempts enable row level security; alter table public.student_responses enable row level security; alter table public.ai_conversations enable row level security; alter table public.decision_checkpoints enable row level security; alter table public.preparation_briefs enable row level security; alter table public.reflections enable row level security; alter table public.faculty_insights enable row level security;

create function public.is_course_faculty(target_course uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from courses where id=target_course and faculty_id=auth.uid()) $$;
create policy "profile self read" on public.profiles for select using(id=auth.uid());
create policy "course members read" on public.courses for select using(exists(select 1 from enrollments e where e.course_id=id and e.user_id=auth.uid()));
create policy "enrollment self or faculty read" on public.enrollments for select using(user_id=auth.uid() or is_course_faculty(course_id));
create policy "assignment members read" on public.assignments for select using(exists(select 1 from enrollments e where e.course_id=course_id and e.user_id=auth.uid()));
create policy "attempt owner read write" on public.student_attempts for all using(student_id=auth.uid()) with check(student_id=auth.uid());
create policy "response owner read write" on public.student_responses for all using(exists(select 1 from student_attempts a where a.id=attempt_id and a.student_id=auth.uid())) with check(exists(select 1 from student_attempts a where a.id=attempt_id and a.student_id=auth.uid()));
create policy "faculty insight course faculty" on public.faculty_insights for select using(exists(select 1 from assignments a where a.id=assignment_id and is_course_faculty(a.course_id)));
-- Production hardening: add equivalent owner/faculty policies for checkpoints, briefs,
-- reflections and conversations; expose cohort aggregation through a security-definer RPC
-- that returns only k-anonymous groups (never raw peer responses).
