"use client";
import { useEffect,useState } from "react"; import { caseStudy,studentResponses } from "@/lib/data"; import { Clock3, GripVertical, Save, Sparkles } from "lucide-react";
const initial=[
 {time:"0–8",title:"Opening commitment",body:"If Hikari had to sign one agreement today, which path should it choose—and what single fact carries your decision?"},
 {time:"8–20",title:"Make speed measurable",body:"Contrast acquisition advocates with organic-entry advocates. Define what 'too slow' means and identify the cost of delay."},
 {time:"20–35",title:"Stress-test the joint venture",body:"Test the assumption that access to 18,000 outlets produces effective distribution. Surface service level, incentives, and governance."},
 {time:"35–48",title:"Put execution on the board",body:"Compare capital, control, time-to-scale, localization, and organizational capacity across all three modes."},
 {time:"48–57",title:"Force a reversal",body:"Ask each position what new evidence would make them switch. Probe high-confidence, weak-support arguments first."},
 {time:"57–60",title:"Closing synthesis",body:"Good entry strategy is a sequence of commitments, not only a mode. Name the no-regret first move and the next decision gate."},
];
export function DiscussionPlan(){const [duration,setDuration]=useState<60|90>(60);const [items,setItems]=useState(initial);const [saved,setSaved]=useState(false);const [mode,setMode]=useState("");useEffect(()=>{fetch("/api/ai/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:{duration:60,responses:studentResponses,caseSources:caseStudy.sources}})}).then(async response=>{const payload=await response.json();if(response.ok){let start=0;setItems(payload.data.segments.map((segment:{minutes:number;title:string;prompt:string})=>{const item={time:`${start}–${start+segment.minutes}`,title:segment.title,body:segment.prompt};start+=segment.minutes;return item}));setMode(payload.mode)}}).catch(()=>{})},[]);return <main className="shell py-10 sm:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">AI-proposed · faculty editable {mode&&`· ${mode} mode`}</div><h1 className="serif mt-3 text-4xl">Discussion plan</h1><p className="mt-2 text-[#68727b]">Built from cohort positions, evidence use, and reasoning gaps.</p></div><div className="flex gap-2"><button onClick={()=>setDuration(60)} className={`btn-secondary ${duration===60?"!bg-[#10283f] !text-white":""}`}>60 min</button><button onClick={()=>setDuration(90)} className={`btn-secondary ${duration===90?"!bg-[#10283f] !text-white":""}`}>90 min</button></div></div>
<div className="mt-10 grid gap-10 lg:grid-cols-[1fr_300px]"><section><div className="divide-y rule border-y rule">{items.map((item,i)=><article key={i} className="grid grid-cols-[28px_55px_1fr] gap-3 py-6"><GripVertical className="mt-1 text-[#9ca2a5]" size={17}/><span className="serif text-[#9a7336]">{duration===90&&i>0?item.time.replace(/\d+/g,n=>String(Math.round(Number(n)*1.5))):item.time}</span><div><input aria-label={`Topic ${i+1} title`} value={item.title} onChange={e=>setItems(x=>x.map((v,j)=>j===i?{...v,title:e.target.value}:v))} className="w-full bg-transparent font-bold"/><textarea aria-label={`Topic ${i+1} detail`} value={item.body} onChange={e=>setItems(x=>x.map((v,j)=>j===i?{...v,body:e.target.value}:v))} className="mt-2 min-h-16 w-full resize-none bg-transparent text-sm leading-6 text-[#68727b]"/></div></article>)}</div><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)}} className="btn-primary mt-7"><Save size={15}/>{saved?"Saved":"Save plan"}</button></section><aside><div className="paper rounded-2xl p-6"><div className="flex gap-2 font-bold"><Sparkles className="text-[#a27b3c]" size={18}/>Board plan</div><ol className="mt-5 space-y-4 text-sm"><li><b>I.</b> Decision criteria</li><li><b>II.</b> Acquisition / JV / Organic</li><li><b>III.</b> Speed ↔ control ↔ capital</li><li><b>IV.</b> Decision gates</li></ol></div><div className="mt-5 flex gap-2 text-xs leading-5 text-[#68727b]"><Clock3 size={16} className="shrink-0"/>Generated content is a starting point. Faculty retain control over sequence, framing, and released feedback.</div></aside></div></main>}
