"use client";
import { useEffect,useState } from "react"; import Link from "next/link"; import { caseStudy,demoBrief } from "@/lib/data"; import { CheckCircle2, Download, RotateCcw, Sparkles } from "lucide-react";
type Attempt={position?:string;rationale?:string;risk?:string;mitigation?:string;confidence?:number;evidence?:string;uncertainty?:string};
export function PreparationBrief(){const [attempt,setAttempt]=useState<Attempt>({});const [reflection,setReflection]=useState("");const [compared,setCompared]=useState(false);useEffect(()=>{const timer=window.setTimeout(()=>{try{setAttempt(JSON.parse(localStorage.getItem("caseflow-attempt")||"{}"))}catch{}},0);return()=>window.clearTimeout(timer)},[]);const recommendation=attempt.position?`${attempt.position}: ${attempt.rationale||demoBrief.recommendation}`:demoBrief.recommendation;
return <main className="shell py-10 sm:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Preparation complete</div><h1 className="serif mt-2 text-4xl">Your pre-class brief</h1><p className="mt-2 text-sm text-[#68727b]">Generated from your reasoning—not a model answer.</p></div><button onClick={()=>window.print()} className="btn-secondary"><Download size={15}/>Print / save PDF</button></div>
<article className="paper mt-8 rounded-2xl p-6 sm:p-10"><header className="border-b rule pb-7"><div className="flex gap-3 text-sm text-[#55705e]"><CheckCircle2 size={18}/>Ready for class</div><h2 className="serif mt-4 max-w-3xl text-3xl">{caseStudy.title}</h2><div className="mt-4 flex flex-wrap gap-3 text-xs font-bold text-[#68727b]"><span>{caseStudy.course}</span><span>•</span><span>Confidence {attempt.confidence||demoBrief.confidence}%</span><span>•</span><span>All figures fictional</span></div></header><div className="mt-8 grid gap-8 lg:grid-cols-2"><BriefBlock n="01" title="Recommendation"><p>{recommendation}</p></BriefBlock><BriefBlock n="02" title="Supporting evidence"><ul>{(attempt.evidence?[attempt.evidence]:demoBrief.evidence).map(x=><li key={x}>{x}</li>)}</ul></BriefBlock><BriefBlock n="03" title="Assumptions"><ul>{demoBrief.assumptions.map(x=><li key={x}>{x}</li>)}</ul></BriefBlock><BriefBlock n="04" title="Trade-offs"><p>{demoBrief.tradeoffs}</p></BriefBlock><BriefBlock n="05" title="Strongest counterargument"><p>{demoBrief.counterargument}</p></BriefBlock><BriefBlock n="06" title="Open question for class"><p>{attempt.uncertainty||demoBrief.question}</p></BriefBlock></div><div className="mt-9 border-t rule pt-5 text-xs text-[#68727b]">Source references: [S2] Strategic options · [S3] Consumer research · [S5] Partner profile. AI inference should be verified against the original case.</div></article>
<section className="mt-12 border-t rule pt-10"><div className="eyebrow">Post-class reflection</div><h2 className="serif mt-3 text-3xl">What changed in your thinking?</h2><p className="mt-2 text-[#68727b]">Return after class to compare the reasoning—not just the answer.</p><textarea value={reflection} onChange={e=>setReflection(e.target.value)} className="mt-6 min-h-32 w-full rounded-xl border rule bg-[#fffdf8] p-4" placeholder="Which assumption was weakest? What evidence changed your position?"/><button onClick={()=>reflection.trim()&&setCompared(true)} className="btn-primary mt-4"><RotateCcw size={15}/>Compare reasoning</button>{compared&&<div className="mt-5 rounded-xl bg-[#e9e2d4] p-5 text-sm leading-7 fade-up"><div className="flex gap-2 font-bold"><Sparkles size={17} className="text-[#9a7336]"/>Reasoning shift</div><p className="mt-2">Your pre-class view emphasized distribution speed. Your reflection introduces governance quality as a decisive condition. The position may be unchanged, but the reasoning is now more conditional and testable.</p></div>}</section>
<div className="mt-10 flex flex-wrap gap-3"><Link href="/student" className="btn-secondary">Back to dashboard</Link><Link href="/faculty" className="btn-secondary">View faculty demo</Link></div></main>}
function BriefBlock({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="border-t rule pt-5"><div className="flex gap-4"><span className="serif text-[#a27b3c]">{n}</span><div className="text-sm leading-7 [&_ul]:list-disc [&_ul]:pl-4"><h3 className="mb-2 font-bold">{title}</h3>{children}</div></div></section>}
