import { demoBrief } from "@/lib/data";
export const fallbacks={
 coach:{question:"What must be true for outlet access to become effective distribution?",challenge:"The partner's 18,000-outlet access [S5] does not establish service levels or sell-through.",sourceIds:["S5"],inference:"AI inference: governance design may matter more than the headline outlet count."},
 brief:{recommendation:demoBrief.recommendation,evidence:demoBrief.evidence,assumptions:demoBrief.assumptions,tradeoffs:demoBrief.tradeoffs,counterargument:demoBrief.counterargument,openQuestion:demoBrief.question,confidence:demoBrief.confidence},
 cohort:{misconceptions:[{title:"Outlet access equals coverage",evidence:"Three responses overgeneralize [S5].",count:3}],overlookedSourceIds:["S4"],discussionTensions:["Speed versus integration capacity","Control versus staged commitment"]},
 plan:{openingQuestion:"Which fact carries your decision?",segments:[{minutes:8,title:"Opening commitment",prompt:"Choose a path and name its decisive fact."},{minutes:20,title:"Stress-test speed",prompt:"Define the cost of delay."},{minutes:32,title:"Compare execution",prompt:"Test governance and integration."}],boardPlan:["Decision criteria","Three entry modes","Decision gates"],closingSynthesis:"Entry is a sequence of commitments, not only a mode."},
 reflection:{positionShift:"The position remained stable.",reasoningShift:"The rationale became more conditional on governance quality.",weakenedAssumption:"Outlet access translates directly into effective reach.",newEvidence:"Operating capacity [S4] gained importance."}
};
export function getDemoFallback(feature:keyof typeof fallbacks,input:unknown){const context=(input&&typeof input==="object"?input:{}) as Record<string,unknown>;const student=(context.student&&typeof context.student==="object"?context.student:context.preClass&&typeof context.preClass==="object"?context.preClass:{}) as Record<string,unknown>;
 if(feature==="coach"&&student.recommendation)return {...fallbacks.coach,question:`You recommend “${student.recommendation}”. What must be true for that choice to outperform the next-best option?`,challenge:`Which source most weakens your claim that “${student.evidence||"the evidence supports this path"}”?`};
 if(feature==="brief"&&student.position){const sourceId=String(student.evidence||"").match(/S[1-5]/)?.[0]||"S2";return {...fallbacks.brief,recommendation:`${student.position}: ${student.rationale||student.recommendation}`,evidence:[{claim:String(student.evidence||"Student-cited evidence"),sourceId}],assumptions:[String(student.coachResponse||student.uncertainty||"The key execution assumption remains untested.")],tradeoffs:`Key risk: ${student.risk||"execution uncertainty"}. Mitigation: ${student.mitigation||"stage the commitment"}.`,openQuestion:String(student.uncertainty||fallbacks.brief.openQuestion),confidence:Number(student.confidence)||fallbacks.brief.confidence};}
 if(feature==="cohort"&&Array.isArray(context.responses)){const responses=context.responses as Array<Record<string,unknown>>;const accessCount=responses.filter(r=>/access|outlet|distribution/i.test(String(r.assumption||""))).length;const cited=new Set(responses.flatMap(r=>Array.isArray(r.evidence)?r.evidence.map(String):[]));return {...fallbacks.cohort,misconceptions:[{title:"Distribution access is treated as effective reach",evidence:`${accessCount} responses use access, outlet, or distribution assumptions.`,count:accessCount}],overlookedSourceIds:["S1","S2","S3","S4","S5"].filter(id=>!cited.has(id)||responses.filter(r=>Array.isArray(r.evidence)&&r.evidence.includes(id)).length<responses.length/3)};}
 if(feature==="reflection"){const post=String(context.postClass||"");return {...fallbacks.reflection,positionShift:`Compared with the pre-class ${student.position||"position"}, the reflection now emphasizes: ${post.slice(0,140)}${post.length>140?"…":""}`,reasoningShift:"The reasoning adds post-class evidence and makes the original recommendation more conditional.",weakenedAssumption:String(student.uncertainty||fallbacks.reflection.weakenedAssumption),newEvidence:post||fallbacks.reflection.newEvidence};}
 return fallbacks[feature];}
