import Link from "next/link"; import { AppNav } from "@/components/app-nav"; import { AssignmentSetup } from "@/components/assignment-setup"; import { CohortAISummary } from "@/components/cohort-ai-summary"; import { caseStudy,studentResponses } from "@/lib/data"; import { cohortMetrics } from "@/lib/analytics"; import { requireCaseFlowRole } from "@/lib/insforge/server"; import { ArrowRight, AlertTriangle, Eye, Quote } from "lucide-react";
export default async function Insight(){await requireCaseFlowRole("faculty");const m=cohortMetrics();const sourceTitle=Object.fromEntries(caseStudy.sources.map(s=>[s.id,s.title]));const evidence=Object.entries(m.evidenceCounts).sort((a,b)=>b[1]-a[1]);return <><AppNav role="faculty"/><main className="shell py-10 sm:py-14"><div className="max-w-3xl"><div className="eyebrow">Cohort insight · anonymized</div><h1 className="serif mt-3 text-4xl leading-tight">Where the room is ready—and where it is brittle.</h1><p className="mt-3 text-[#68727b]">Derived from {m.total} synthetic submissions for the fictional Hikari Foods case. No student identities are shown.</p></div>
<section className="mt-12 grid gap-10 lg:grid-cols-2"><div className="paper rounded-2xl p-6 sm:p-8"><div className="eyebrow">Position distribution</div><div className="mt-8 space-y-6">{Object.entries(m.positions).map(([label,n])=><div key={label}><div className="flex justify-between text-sm font-bold"><span>{label}</span><span>{n} · {Math.round(n/m.total*100)}%</span></div><div className="mt-2 h-2 rounded-full bg-[#e3ded4]"><div className="h-full rounded-full bg-[#10283f]" style={{width:`${n/m.total*100}%`}}/></div></div>)}</div></div><div className="paper rounded-2xl p-6 sm:p-8"><div className="eyebrow">Evidence use</div><div className="mt-7 space-y-4">{evidence.map(([id,n])=><div className="grid grid-cols-[1fr_auto] gap-4 border-b rule pb-3 text-sm" key={id}><span><b className="text-[#9a7336]">[{id}]</b> {sourceTitle[id]}</span><span className="font-bold">{n} cites</span></div>)}</div></div></section>
<section className="mt-12"><div className="eyebrow">Reasoning gaps to test</div><CohortAISummary/><div className="mt-5 divide-y rule border-y rule">{[
 [AlertTriangle,"Distribution access ≠ effective reach",`${m.accessAssumptionCount} responses rely on access, outlet, or distribution assumptions. Ask what service level, shelf placement, and sell-through would have to be true.`,"High confidence · weak support"],
 [Eye,"Integration capacity is underweighted",`${m.overlookedOperatingRisk} of ${m.total} responses omit [S4]. Contrast control on paper with Hikari’s ability to integrate.`,"Frequently overlooked evidence"],
 [Quote,"Localization is treated as costless",`${m.localizationAssumptionCount} arguments mention localization, flavor, brand, or premium positioning without consistently pricing operating complexity.`,"Common hidden assumption"]
 ].map(([Icon,title,text,tag])=><article key={String(title)} className="grid gap-4 py-6 sm:grid-cols-[32px_1fr_auto]"><Icon className="text-[#a27b3c]" size={20}/><div><h3 className="font-bold">{String(title)}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#68727b]">{String(text)}</p></div><span className="h-fit rounded-full bg-[#e9e2d4] px-3 py-1 text-xs font-bold">{String(tag)}</span></article>)}</div></section>
<section className="mt-12 grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div><div className="eyebrow">Representative arguments</div><div className="mt-5 space-y-4">{studentResponses.filter((_,i)=>[0,4,6].includes(i)).map(r=><blockquote key={r.id} className="border-l-2 border-[#b48a43] pl-5 text-sm leading-7"><p>“{r.rationale}”</p><footer className="mt-2 text-xs font-bold text-[#68727b]">Anonymous {r.id} · {r.position} · {r.confidence}% confidence</footer></blockquote>)}</div></div><aside className="rounded-2xl bg-[#10283f] p-7 text-white"><div className="eyebrow !text-[#d6b77e]">Turn insight into teaching</div><h2 className="serif mt-4 text-3xl">Build the room around productive disagreement.</h2><p className="mt-3 text-sm leading-6 text-[#cfdae1]">Generate an editable 60-minute sequence grounded in these observed patterns.</p><Link href={`/faculty/cases/${caseStudy.id}/discussion-plan`} className="mt-7 inline-flex items-center gap-2 font-bold text-[#e0bd7d]">Create discussion plan <ArrowRight size={16}/></Link></aside></section>
<AssignmentSetup/></main></>}
